#!/usr/bin/env bash
# Idempotent Cloud Agent bootstrap for apidame-web.
# Installs the pinned Node toolchain, project deps, and a local libSQL DB
# seeded from scripts/seed so the app runs end-to-end without remote Turso.
set -euo pipefail

cd "$(dirname "$0")/.."

export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
if [ ! -s "$NVM_DIR/nvm.sh" ]; then
  echo "nvm not found at $NVM_DIR; cannot provision Node 24" >&2
  exit 1
fi
# shellcheck disable=SC1091
. "$NVM_DIR/nvm.sh"

NODE_VERSION="$(cat .nvmrc 2>/dev/null || echo 24)"
nvm install "$NODE_VERSION" >/dev/null
nvm use "$NODE_VERSION" >/dev/null
export PATH="$NVM_BIN:$PATH"

if ! command -v yarn >/dev/null 2>&1; then
  npm install -g yarn@1.22.22 >/dev/null
fi

echo "node $(node -v) / yarn $(yarn -v)"

yarn install --frozen-lockfile

if [ ! -f .env.local ]; then
  echo "Creating .env.local for local development"
  AUTH_SECRET_VALUE="$(node -e "console.log(require('crypto').randomBytes(32).toString('base64'))")"
  cat > .env.local <<EOF
# Local development config generated by .cursor/setup.sh.
# Uses a local libSQL/SQLite file instead of remote Turso (no real secrets).
# To use real integrations, fill these in or override via Cloud Agent secrets.
TURSO_DATABASE_URL=file:local.db
TURSO_DATABASE_TOKEN=local-dev
AUTH_SECRET=$AUTH_SECRET_VALUE
AUTH_TRUST_HOST=true
ADMIN_EMAIL=elevyg91@gmail.com
NEXT_PUBLIC_POSTHOG_HOST=https://us.i.posthog.com
EOF
fi

yarn db:push

if [ "${SKIP_SEED:-0}" != "1" ]; then
  yarn db:seed
fi

echo "Setup complete."
